### ISSUE TITLE
Typing in endorsement page combo box causes page to display "Unexpected error"

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#2385]
# Current behavior

Typing anything in the peer endorsements combo box causes the page to immediately crash and display "Unexpected error". See screen recording below.

https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/5fea72e2-7428-46ba-b74a-200e83ac3bc1

# Expected behavior

Page should perform request to load combo box data.

# Steps to reproduce

1. Go to https://test.gcn.nasa.gov/user/endorsements
2. Start typing in the combo box.

# Environment

All browsers and operating systems.

**Comment by lpsinger** [comment]
The request is being blocked by [AWS WAF](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-awswaf.html). Here is the response:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: OI-gIxWdZW3ttLjt--LuFUeDrLJKcsARo_xGnqaxvVjEhlKkFRuCyg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

I have disabled AWS WAF on production until we resolve the issue.

However, after addressing the AWS WAF issue, there is still a problem with rate limits when one types very rapidly; if one does, there is the risk that we will hit the AWS Cognito API rate limit when generating the combo box contents; in this case we get the following error message in our Lambda's CloudFront log:

```
ERROR	TooManyRequestsException: Too many requests
    at de_TooManyRequestsExceptionRes (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/index.js:4141:21)
    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/index.js:3777:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at makePagedClientRequest (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:430:10)
    at paginateOperation (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:443:16)
    at n8e (/var/task/index.cjs:900:1448) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '...',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 1047
  },
  __type: 'TooManyRequestsException'
}
```
