### ISSUE TITLE
circulars archive browsing error

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#700]
On dev, I tried clicking on the largest numbered page in the archive (334), and got he following error.

`Error: Unexpected Server Error
    at Ift (/var/task/index.js:14:8921)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /var/task/index.js:14:7644
    at Runtime.<anonymous> (/var/task/index.js:112:7519)`

**Comment by lpsinger** [comment]
Fixed now by properly normalizing some old circulars.
